# Generated by Django 4.2.4 on 2023-09-19 19:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("image_uploader", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedimage",
            name="thumbnail_200",
        ),
        migrations.RemoveField(
            model_name="uploadedimage",
            name="thumbnail_400",
        ),
    ]
